### ISSUE TITLE
deck builder

### ISSUE THREAD

**Issue by seiyria** [LimeLightCards/limelight#19]
like encore, but with the following features:

- [x] view all decks
	- [x]  search/filter (?) using the existing search page
	- [x] ~~need new query to text~~ #54
	- [x] need new operators that are server side
	- [x] ~~need to document is:deck (and by extension is:card, which is implicit)~~ #53 
	- [x] sorts - last updated, name | asc,desc
- [x] view author profile
	- [x] view decks made
	- [x] aggregated stats about what sets are used
	- [x] embedded "all decks" view, but localized to `author:<id>`
- [x] view features
	- [x] show "parent" deck
	- [x] "fork" option (call it "remix")
		- [x] remix needs to support a revision
	- [x] show when deck was last updated
	- [x] export deck to tsv
	- [x] show revisions
		- [x] load a specific revision
	- [x] link to creator profile
	- [x] ~~support embedding decks as images or lists (https://www.mtggoldfish.com/deck/visual/5228680)~~ #52
	- [x] quick view of stats, breakdowns, and climax combos
	- [x] different sorts - color, level, etc
	- [x] draw 5
	- [x] different views (https://www.mtggoldfish.com/archetype/modern-titan-shift#paper)
		- [x] visual, stacked
		- [x] list 
	- [x] cost to build the deck
		- [x] skip cards / quantities owned
- [x] edit features
	- [x] import deck from tsv
	- [x] support private decks
	- [x] description for decks, user-edited
	- [x] be like mtg goldfish?
	- [x] look at deck stats and convert level/color to chips (?) 
	- [x] cut grid size to half, investigate making swiper move more at a time, put permanent card preview on right side of grid
- [x] search features
	- [x] tie into the search bar or make a separate page for searching (search bar could, by default, add is:card and you could opt in with is:deck)
		- [x] search by deck name
		- [x] search by cards in deck
		- [x] search by deck author
		- [x] search by card attributes in a deck, etc
- [x] updates to card view page
	- [x] X card is used in Y% of decks
	- [x] X card is used in Y decks (show list)

will require user auth (firebase) and storage (firecloud)

as well as warnings that it might not save if you do it offline

https://tapandsac.com/2022/05/what-is-the-best-mtg-deck-builder-website for some examples?
